# Service account for the VAC clients
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vac
rules: []
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vac
subjects:
  - kind: ServiceAccount
    name: vac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vac